name: CI-CD-HTML-to-VPS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "html-test-page-for-cv"
  EB_APPLICATION_NAME       : "HTML-page"
  EB_ENVIRONMENT_NAME       : "Htmlpage-env-1"
  DEPLOY_PACKAGE_NAME       : "html_page_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches:
      - master
      
jobs: 
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v1
      
    - name: Create zip deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment Package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
  my_cd_part:  
     runs-on: ubuntu-latest
     needs: [my_ci_part]
     
     steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }} 
        
     - name: Create new ElasticBeanstalk App
       run : |
         aws elasticbeanstalk create-application-version \
         --application-name ${{ env.EB_APPLICATION_NAME }} \
         --source-bundle S3Bucket= "${{ env.EB_PACKAGE_S3_BUCKET_NAME }}", S3Key="${{ DEPLOY_PACKAGE_NAME }}" \
         --version-label "version-${{ github.sha }}"
      
     - name: Deploy new ElasticBeanstalk App version
       run : aws elasticbeanstalk update-environment --environment-name ${{ EB_ENVIRONMENT_NAME }} --version-label "version-${{ github.sha }}"
        
        
        
     
 
